name: Window

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: download ngrok
        shell: powershell
        run: | & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AdQt8qggs4G0-fsIdd1XG2GEvC3-8g61KHzvoMJ52wVByKYgJ5y_xtigCQcpDlWtQ-MeeQ" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME
      - name: Run loop
        run: ping -t localhost
